include:
  - project: 'shared/ci-utils'
    file: 'triply-etl.yml'

default:
  tags:
    - docker-socket

stages:
  - release
  # 0: Only install, lint and build, gets triggered on push and merge-requests:
  - preflight
  - run-application

image: ${CI_REGISTRY_IMAGE}:24.05.23

# - Uses the docker image, so we have the docker credentials
# - Logs-in to the registry of that project (CI_REGISTRY) using the credentials of the person who triggered the CI (CI_REGISTRY_USER).
# - It publishes using the project name of your project (CI_REGISTRY_NAME) is something like
# - Releases / pushes the image
release-docker:
  image: docker:20.10.18-cli
  stage: release
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}:24.07.02 .
    - docker push ${CI_REGISTRY_IMAGE}:24.07.02

main:
  stage: run-application
  interruptible: true
  allow_failure: false
  script:
    - npm install
    - npm run build
    - node --max-old-space-size=16000 lib/main.js --ifc=Kievitsweg_R23_MVP_IFC4.ifc --ids="IDS Rotterdam BIM.ids" --clean
